from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.documents import Document
from typing import List
from pydantic import BaseModel, Field

def split_text(text, chunk_size=1000, chunk_overlap=200):
    """
    Splits text into chunks using RecursiveCharacterTextSplitter with custom logic.
    If text length is less than 1.5 * chunk_size, returns a single chunk.
    Otherwise, splits with specified overlap.
    Returns a list of Document objects.
    """
    if not text:
        return []
        
    # Custom logic: if text is short enough, keep it whole
    if len(text) < (chunk_size * 1.5):
        return [Document(page_content=text)]
        
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", " ", ""]
    )
    return text_splitter.create_documents([text])


class Section(BaseModel):
    """A logical section of the document."""
    summary: str = Field(description="A brief summary or description of what this section covers.")
    content: str = Field(description="The exact original text of the section. Do not modify it.")

class PageSections(BaseModel):
    """The structured output containing all sections of the page."""
    sections: List[Section]

def split_text_with_llm(text, model_name="gpt-5-mini"):
    """
    Splits the full text into logical sections using an LLM.
    Returns a list of Document objects, where each document is a section.
    Metadata includes the summary generated by the LLM.
    """
    if not text:
        return []
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(PageSections)
    
    prompt = (
        "You are a technical documentation processor.\n"
        "Split the provided documentation page into logically distinct sections.\n"
        "For each section, provide:\n"
        "1. A brief summary/description.\n"
        "2. The exact original text of that section (preserve formatting as much as possible).\n"
        "\n"
        "TEXT:\n{text}"
    )
    
    try:
        chain = prompt | structured_llm
        result = chain.invoke({"text": text})
        documents = []
        for section in result.sections:
            # User Strategy: Embed Summary, Retrieve Original via Metadata
            doc = Document(
                page_content=section.summary,  # This is what gets embedded
                metadata={
                    "original_content": section.content, # This is the full context
                    "type": "llm_semantic_chunk"
                }
            )
            documents.append(doc)
        return documents
    except Exception as e:
        print(f"Error during LLM splitting: {e}")
        # Fallback to simple splitting if LLM fails
        return split_text(text)

def enhance_chunk_with_llm(chunk_text, llm=None):
    """
    Uses LLM to generate a concise summary or keywords for the chunk.
    This metadata can be stored with the chunk for better retrieval.
    """
    if not llm:
        llm = ChatOpenAI(model="gpt-5-mini", temperature=0)

    prompt = PromptTemplate.from_template(
        "Summarize the key technical concepts in the following text in 1 sentence:\n\n{text}"
    )
    chain = prompt | llm
    try:
        summary = chain.invoke({"text": chunk_text})
        return summary.content
    except Exception as e:
        print(f"Error enhancing chunk: {e}")
        return ""

def process_documents(documents, use_llm=False):
    """
    Iterates through documents and optionally adds LLM-generated metadata.
    """
    if use_llm:
        print(f"Enhancing {len(documents)} chunks with LLM...")
        llm = ChatOpenAI(model="gpt-5-mini", temperature=0)
        for i, doc in enumerate(documents):
            print(f"Processing chunk {i+1}/{len(documents)}...")
            summary = enhance_chunk_with_llm(doc.page_content, llm)
            doc.metadata["summary"] = summary
    return documents
